version: "3.7"

services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - "8601:8601"

  frontend:
    container_name: frontend
    build:
      context: "./frontend-ui"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
